# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VendingMachine' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftLint'
  # Pods for VendingMachine

  target 'VendingMachineTest' do
    inherit! :search_paths
    # Pods for testing
  end

end
